### ISSUE TITLE
Missing separator error in Makefile.common.footer

### ISSUE THREAD

**Issue by akonneker** [dkogan/mrbuild#2]
I'm trying to use mrbuild to make mrgingham, and have run into the following error:

`mrbuild/Makefile.common.footer:360: *** missing separator.  Stop.`

I am pretty ignorant when it comes to make, but my google-fu has led me to believe it may be an issue with mixing tabs and spaces? In any case, converting some of the leading indentation into tabs around that line seemed to fix the issue. 

I'm running this in zsh on MacOS, fyi.

**Comment by dkogan** [comment]
Hi. I need more information. Where did your copy of mrbuild come from? Did you change anything? If you did change something, does the build work when those changes are reverted?
Thanks.

**Comment by nbelanger99** [comment]
Hi, also having this issue with v1.1 on MacoS (both zsh and bash)

**Comment by dkogan** [comment]
OK. I'm guessing you're using an old or crippled Make. What does `make -v` say?

**Comment by dkogan** [comment]
Closing for lack of info
